export const BulletinData = [
    {   author: 'Charles Malave',
        subject: 'e pluribus unum',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},
{   author: 'Ian Judd',
    subject: 'da homie',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},    
{   author: 'Travis Woolston',
    subject: 'Best Float Tanks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},  
{   author: 'Damian Allert',
    subject: 'how to win at life',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},
{   author: 'Randy Diebold',
    subject: 'How To Fix Anything',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},
{   author: 'Ian Judd',
    subject: 'da homie',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},    
{   author: 'Travis Woolston',
    subject: 'Best Float Tanks',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},  
{   author: 'Damian Allert',
    subject: 'how to win at life',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},
{   author: 'Randy Diebold',
    subject: 'How To Fix Anything',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pharetra mauris vel mi tincidunt, eget consectetur neque luctus. Mauris ac nisl massa. Vestibulum tristique ac enim quis mattis. Donec quis mauris erat. Integer eget justo at eros ultrices egestas. Suspendisse eleifend tortor ac nisi scelerisque posuere. Donec nec semper augue, a semper leo. Donec pulvinar leo ligula, a ultricies erat hendrerit eget. Nunc at consectetur dolor, eget tincidunt nisi. Etiam ultrices, arcu et convallis congue, orci arcu efficitur quam, eu eleifend augue urna eget massa. Morbi rutrum blandit orci eget volutpat. Morbi faucibus purus sapien, et mollis augue faucibus id. Morbi ac aliquet magna. Phasellus a erat sollicitudin, semper nisi vitae, venenatis justo. Morbi quis faucibus arcu. Integer ut bibendum risus.'
},
]